---
title: "Data Import"
output: github_document
---

This file is for data imports.

# Load Packages
```{r}
library(tidyverse)
library(readxl)
```

## Load first data set:
```{r}
## Import litter df:
litters_df =
  read_csv(file = "data/FAS_litters.csv", 
           na = c('.', "NA", ""))

## Change column labels to snake case.
litters_df = janitor::clean_names(litters_df)
```

## Load second data set:
```{r}
## Import pups df:
pups_df =
  read_csv("data/FAS_pups.csv", 
           skip = 3, 
           na = c('.', "NA", ""))

## Change column labels to snake case.
pups_df = janitor::clean_names(pups_df)
```

## Look at data head/tail:
```{r}
head(litters_df)

tail(pups_df)
```


## Skim to summarize info about data.
```{r}
skimr::skim(pups_df)
```

## Oh excel ...
```{r}
# Load mlb data:
mlb_df = read_excel("data/mlb11.xlsx")
```

### Look at excel data:
```{r}
head(mlb_df)
```

## Load some LOTR data:
```{r}
# Load FOTR:
fotr_df = read_excel("data/LotR_Words.xlsx", 
                     range = "B3:D6")

fotr_df

# Load two towers:
tt_df = read_excel("data/LotR_Words.xlsx", 
                     range = "F3:H6")

tt_df
```



